### ISSUE TITLE
Failed to load assembly (Lidgren.Network)

### ISSUE THREAD

**Issue by AwouldLikeM** [RAGECOOP/RAGECOOP-V#50]
The 'Lidgren.Network.dll' file is missing from the newest [release](https://github.com/RAGECOOP/RAGECOOP-V/releases/tag/1.5.4).
![image](https://github.com/RAGECOOP/RAGECOOP-V/assets/134278567/a65d8bcb-dc4c-4523-b982-d57ec9fe38d0)

Downloading and adding the file manually fixes the issue.

**Comment by oldnapalm** [comment]
This message is normal, the mod will work despite of it, you don't need to download the file manually.

**Comment by oldnapalm** [comment]
It's been found that downloading Lidgren.Network.dll and putting in Scripts folder is not only unnecessary but can also cause FPS drops if you use a debug version, because it will be used instead of the built-in version which has better performance.

https://discord.com/channels/920774603570294896/1164313878872719460
